### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by emmiiorji** [emmiiorji/recipe-app#10]
This is a group of two: @kiboma2021 and @emmiiorji taking part in the [Recipe App project](https://github.com/users/emmiiorji/projects/1)

**Comment by omar-muhamad** [comment]
# Changes Required ♻️
### Hi @emmiiorji and @kiboma2021,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Changes Required) Aspects to improve: ♻️

- [ ] Please add a proper description to the first kanban card because all cards suppose to have a description.

![image](https://user-images.githubusercontent.com/68796232/200387631-dde31fb7-57e9-4759-b298-3ec96cafb9c7.png)

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
